### ISSUE TITLE
Missing startup script

### ISSUE THREAD

**Issue by bygui86** [BillyFnh/k8s-mongo-replicaset#1]
Hi @BillyFnh and @Fireball889 

Your article [here](https://medium.com/swlh/how-to-setup-mongodb-replica-set-on-kubernetes-in-minutes-5c1e7fd5b5f3) is great.

But I have a question :(

In this repo you don't have any `startup-script-mongo` folder or any `startup-*.sh` file, but in Dockerfile you copy/use them:

```Dockerfile
# ...

COPY /startup-script-mongo /root

CMD ./startup-$MONGODB_ID.sh
```

Can you add to this repo the folder or the script? or can you provide at least the script somehow?

Thanks in advance for your help!

**Comment by BillyFnh** [comment]
Hi @bygui86,

Thanks for letting me know, I just added the missing source file under `./source/startup-script-mongo/.
Inside the folder you'll find startup-mongo-0.sh/startup-mongo-1.sh/startup-mongo-2.sh.

Do let me know if you have any more questions!

**Comment by rajat-soda** [comment]
Hi @BillyFnh , 

The article is really great.. however while trying out the sample with 'hostPath' I am running into issues. The Mongo Replicaset is up .. but I am not able to access it using the connection string  " mongodb://mongodb-0-service:27017,mongodb-1-service:27017,mongodb-2-service:27017/admin?replicaSet=rs0"
